### ISSUE TITLE
Publish v1.1.0

### ISSUE THREAD

**Issue by rreusser** [stackgl/gl-vec2#10]
Oops. Looks like I don't have npm rights, @mattdesl. Glad to make any changes/amendments before publishing, but otherwise, I've added tests and most of the functions that gl-matrix has (excluding `str` and `inverse`), so I think it's good to go.

**Comment by mattdesl** [comment]
Ah no worries. I’ll add you to this and other modules when I’m back at my computer in an hour or so.

**Comment by mattdesl** [comment]
Alright you should have npm access to the gl-vec/mat/quat modules now. Thanks again for all your help!
