### ISSUE TITLE
sub / etc - shorthand

### ISSUE THREAD

**Issue by mattdesl** [stackgl/gl-vec2#2]
I think it would probably be worth adding shorthand functions for things like `vec2.sub`.

The way it would be implemented, to minimize duplication:

- `sub` is added to `index.js` so it can be referenced as `vec2.sub`, it points to `require('./sub')`
- `sub.js` file is added, which just does `module.exports = require('./subtract')`

This way user can `require('gl-vec2/sub')` or `require('gl-vec2/subtract')` or `require('gl-vec2').sub` and it all points to the same function.

Same for other shorthands in gl-matrix modules, there are quite a few:
http://glmatrix.net/docs/module-vec2.html

**Comment by rreusser** [comment]
Merged. Next up is the remaining stackgl modules. 😬
