### ISSUE TITLE
lagging behind gl-matrix

### ISSUE THREAD

**Issue by mattdesl** [stackgl/gl-vec2#3]
This is lagging behind gl-matrix a bit. I don't think it's a huge problem, the goal isn't to be 100% exactly the same as gl-matrix, this module can probably start to form its own unique identity. But overall it would be nice to pull in a few things like equals, exactEquals, floor, ceil, etc.

http://glmatrix.net/docs/module-vec2.html

Same also goes for mat4/vec3/etc.

**Comment by rreusser** [comment]
Candidates for addition to this module, in checklist form
- [x] len (#4)
- [x] sub (#4)
- [x] mul (#4)
- [x] div (#4)
- [x] dist (#4)
- [x] sqrDist (#4)
- [x] sqrLen (#4)
- [x] ceil (#5)
- [x] round (#5)
- [x] floor (#5)
- [x] inverse (#11)
- [ ] str
- [x] exactEquals (#6)
- [x] equals (#6)

For reference, here's a list of functions in gl-matrix but not in the stackgl modules:

```javascript
missingFuncs: {
  vec2: [
    len, sub, mul, div, dist, sqrDist, sqrLen, ceil, floor, round, inverse,
    str, exactEquals, equals
  ],  
  vec3: [
    sub, mul, div, dist, sqrDist, len, sqrLen, ceil, floor, round, hermite,
    bezier, str, exactEquals, equals
  ],  
  vec4: [
    sub, mul, div, dist, sqrDist, len, sqrLen, forEach, ceil, floor, round,
    str, exactEquals, equals
  ],  
  mat2: [
    mul, sub, clone, fromValues, set, fromRotation, fromScaling, str, LDU,
    add, subtract, exactEquals, equals, multiplyScalar, multiplyScalarAndAdd
  ],  
  mat3: [
    mul, sub, fromValues, set, fromTranslation, fromRotation, fromScaling,
    fromMat2d, projection, add, subtract, multiplyScalar, multiplyScalarAndAdd,
    exactEquals, equals
  ],  
  mat4: [
    mul, sub, fromValues, set, fromTranslation, fromScaling, fromRotation,
    fromXRotation, fromYRotation, fromZRotation, getTranslation, getScaling,
    getRotation, fromRotationTranslationScale, fromRotationTranslationScaleOrigin,
    targetTo, frob, add, subtract, multiplyScalar, multiplyScalarAndAdd,
    exactEquals, equals
  ],  
  quat: [
    mul, len, sqrLen, exactEquals, equals, getAxisAngle, fromEuler, str 
  ]
}
```

**Comment by rreusser** [comment]
FWIW, I agree they're no sense mirroring gl-matrix identically, but on the other hand, close correspondence could ease the transition. We currently use gl-matrix. I'd love to suggest stackgl instead, but an API that's not in sync makes it a bit of a headache to figure out what's what so that we end up just never switching.

**Comment by rreusser** [comment]
Closing this. Final discussion point is #12, which implicitly applies to the analogous and hopefully-soonish updates to the remaining stackglmatrix modules.
